### ISSUE TITLE
Cannot format due to the following errors

### ISSUE THREAD

**Issue by warpdesign** [vlang/vscode-vlang#118]
Whatever I type, I always get this error:

![image](https://user-images.githubusercontent.com/199648/73132762-a08d4c80-401f-11ea-9727-2768b0fe409b.png)

As you can see, the errors aren't displayed: when expanding the panel, it only shows `Source: V (extension)`.

**Comment by warpdesign** [comment]
Looking at the dev tools console gives some information.

That's what I get when switch to a tab with a v source code:

![image](https://user-images.githubusercontent.com/199648/73132809-3032fb00-4020-11ea-8ab9-5533feb63c48.png)

That's what I get when attempting to save current file:

![image](https://user-images.githubusercontent.com/199648/73132814-4771e880-4020-11ea-93cb-24929560687f.png)

**Comment by dhonx** [comment]
This error is from V

**Comment by mkhennoussi** [comment]
@warpdesign Did you fixed the issue ? Thanks

**Comment by ChildishGiant** [comment]
Basically this seems to happen when there's an error in the code but the error's not being shown in the notification properly. To see it, run `v fmt FILE`

**Comment by maxbertinetti** [comment]
Hi. This happen also to me on Mac Os with latest V and CS Code.
Issuing v fmt [filename.v] from terminal gives no error and with "-w" the file is being formatted correctly.
Still doesn't format from VS Code.
