### ISSUE TITLE
Running Save Participants for '1.v': Formatting

### ISSUE THREAD

**Issue by nklayman** [vlang/vscode-vlang#124]
I get the error even when clearing my settings and disabling all extensions. I am using vscode 1.42 and Manjaro Linux. On vscode v1.41 it works.

Whenever I try and save a file, even with format on save disabled, I get the following notification and nothing saves. When I run `save without format`, it saves fine. If I run `format document`, it works fine as long as there are no unsaved changes, otherwise I get the same notification as running `save`

![image](https://user-images.githubusercontent.com/12448243/73992000-a11cc180-4902-11ea-811b-397e67c92df2.png)

**Comment by dhonx** [comment]
Are you using language-specific settings?

**Comment by nklayman** [comment]
The issue is still present with no custom settings. This was a fresh install of the extension and v.

**Comment by lydiandy** [comment]
when I update to vscode1.42, get the same problem

**Comment by dhonx** [comment]
Thanks for the info...!! Will fix  ✅

**Comment by dhonx** [comment]
References:
https://github.com/James-Yu/LaTeX-Workshop/issues/1939
https://github.com/microsoft/vscode/issues/90273

**Comment by lydiandy** [comment]
thanks,got it

**Comment by alexesprit** [comment]
If you want to stay on VS Code 1.42 you can turn off format on save for V:
```
    "[v]": {
        "editor.formatOnSave": false
    },
```
Just add this setting to your `settings.json`.

I'm on 1.42, and I have this notification only if I remove or comment this setting.
