### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Nagkei10** [vlang/vscode-vlang#125]
- Issue Type: `Performance`
- Extension Name: `vscode-vlang`
- Extension Version: `0.1.1`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.42.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\keito940\0x9ef.vscode-vlang-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by dhonx** [comment]
@keito940 Can you show me the `C:\Users\keito940\0x9ef.vscode-vlang-unresponsive.cpuprofile.txt`

**Comment by danieldaeschle** [comment]
Nothing to inspect, you can reopen if it happens after cleanup.
