### ISSUE TITLE
Spurious "missing main" error shown in vscode

### ISSUE THREAD

**Issue by JalonSolov** [vlang/vscode-vlang#150]
When I bring up the source for any `v` module, vscode always shows this error:

`error project must include a `main` module or be a shared library (compile with `v -shared`)V`

The error should only show up if trying to compile the module as a separate project.

**Comment by dhonx** [comment]
Already fixed on https://github.com/vlang/vscode-vlang/pull/143 & https://github.com/vlang/vscode-vlang/pull/147

**Comment by Serkonda** [comment]
@dhonx fixed but not released as a new version
