### ISSUE TITLE
Publish it on Open VSX

### ISSUE THREAD

**Issue by TheBrainScrambler** [vlang/vscode-vlang#153]
I am currently using VSCodium, which is a Libre build of VSCode without trackers. But it doesn't use the VSCode Marketplace as stated in https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions-marketplace but instead https://open-vsx.org.
Could you please also publish this extension on Open VSX ?
The instructions are available at https://github.com/eclipse/openvsx/wiki/Publishing-Extensions.

**Comment by dhonx** [comment]
Thanks @TheBrainScrambler... I will do that...

**Comment by TheBrainScrambler** [comment]
Thanks goes to you !

**Comment by dhonx** [comment]
@TheBrainScrambler Thank's man,,, but I think it would be better if the original author do that instead...

**Comment by TheBrainScrambler** [comment]
Oops sorry, I thought you were the author. Of course I would just do it myself if it wouldn't be better that the author does it

**Comment by dhonx** [comment]
Hahaha... no... its not me lol

**Comment by alexesprit** [comment]
I think we have a centralized publisher for both marketplaces (either 0x9ef, or another responsible person). VS Code Marketplace allows to have multiple people with publish access.

Having a different people (or teams) for multiple marketplaces might be confusing in some cases.

**Comment by danieldaeschle** [comment]
Can we take https://open-vsx.org/extension/0x9ef/vscode-vlang down after we published it under The V Programming Lanugage?

**Comment by serkonda7** [comment]
The extension is published here https://open-vsx.org/extension/vlanguage/vscode-vlang
