### ISSUE TITLE
Linter works only after save

### ISSUE THREAD

**Issue by AmrBinBashir** [vlang/vscode-vlang#159]
I would like to have the linter spot errors on typing rather than waiting to save the file.

**Comment by ChildishGiant** [comment]
It's a bit of a bodge but you can turn on autosave using this setting
```
"files.autoSave": "afterDelay",
"files.autoSaveDelay": 500
```
Sadly this can't be changed on a per-language basis so you can't have this set up just for v

**Comment by AmrBinBashir** [comment]
@ChildishGiant I can use that for now in the workspace of a V project only.
