### ISSUE TITLE
Persistent Running "V" Formatter message

### ISSUE THREAD

**Issue by ChildishGiant** [vlang/vscode-vlang#163]
When attempting to use the formatter on save it doesn't work and this message appears until you cancel it.
```json
"[v]":{
    "editor.formatOnSave": true,
    "editor.defaultFormatter": "vlang-vscode.extension",
}
```
![stuck](https://user-images.githubusercontent.com/13716824/89675391-bee2d780-d8e1-11ea-9946-496f2f342f16.png)

**Comment by donnisnoni** [comment]
Is this still happen on you @ChildishGiant ?
