### ISSUE TITLE
Highlighting problems when using #include followed by a comment

### ISSUE THREAD

**Issue by MangelMaxime** [vlang/vscode-vlang#171]
Hello, 

the highlith of `#include` statement doesn't stop correctly.

![image](https://user-images.githubusercontent.com/4760796/101074721-61198000-35a1-11eb-925d-7293b466829e.png)

The comment should be colored in green.

![image](https://user-images.githubusercontent.com/4760796/101075022-c40b1700-35a1-11eb-8a46-c4d700438cba.png)

![image](https://user-images.githubusercontent.com/4760796/101074922-a50c8500-35a1-11eb-94a7-148e7af21438.png)

`struct` should be in blue.

![image](https://user-images.githubusercontent.com/4760796/101075052-cb322500-35a1-11eb-8153-fd260c0e6f85.png)

**Comment by 0x9ef** [comment]
May be fixed in https://github.com/vlang/vscode-vlang/commit/d3404d4772ab744fe68361486c81fc6bb0058101 :)

**Comment by danieldaeschle** [comment]
thank you @0x9ef ! =)
