### ISSUE TITLE
setting beak point

### ISSUE THREAD

**Issue by kahsa** [vlang/vscode-vlang#172]
Now setting break points can be only by typing into the place.
It would be nice if it can be by clicking the line number.

![vsv](https://user-images.githubusercontent.com/52106048/101121084-99b56a00-3632-11eb-86be-38ffee108f9e.png)

**Comment by danieldaeschle** [comment]
Fixed in 2eb175e

**Comment by danieldaeschle** [comment]
![image](https://user-images.githubusercontent.com/30751516/101992277-5c944c00-3cb2-11eb-8740-d566b7897d52.png)

**Comment by danieldaeschle** [comment]
![image](https://user-images.githubusercontent.com/30751516/101992299-8188bf00-3cb2-11eb-8668-e551ade61a02.png)
![image](https://user-images.githubusercontent.com/30751516/101992302-85b4dc80-3cb2-11eb-9c1a-2e127238b73d.png)

**Comment by kahsa** [comment]
Fantastic!! Great work! thanks!

**Comment by B-Esmaili** [comment]
Have anyone managed to get debug working in linux environment? I am trying it in `ubuntu` and i get following warning 
`The Task 'build:debug' cannot be tracked. Make sure to have a problem matcher defined` subsequently the debugging fails with no useful log in output tab.

**Comment by vinyll** [comment]
Here the error is "_Could not find the task 'build:debug'._" when copy/pasting the code from the image.
