### ISSUE TITLE
[feat] Delete the automatically generated binary file after running

### ISSUE THREAD

**Issue by d1y** [vlang/vscode-vlang#195]
![Screen Shot 2020-12-26 at 12 31 01](https://user-images.githubusercontent.com/45585937/103145469-3ffa1880-4776-11eb-8597-ecf8bf143bf8.png)

```bash
v run calculator.v && rm -rf calculator
```

**Comment by JalonSolov** [comment]
`v run <whatever.v>` automatically deletes the binary after it is run.  That was added a little while ago.

**Comment by d1y** [comment]
> `v run <whatever.v>` automatically deletes the binary after it is run. That was added a little while ago.

where is it?

**Comment by JalonSolov** [comment]
Get the latest version of V.

**Comment by nedpals** [comment]
Closed. See https://github.com/vlang/vscode-vlang/pull/196#issuecomment-751408395.
