### ISSUE TITLE
editor.action.formatDocument delete all 

### ISSUE THREAD

**Issue by kahsa** [vlang/vscode-vlang#198]
v version: 0.2 d094baf
os:  archlinux
vlang-vscode.extention: 0.1.3

`editor.action.formatDocument` deletes all of code something like
```v
fn main() {
	a = i;
}
```
remains nothing.

while `v frm file.v` returns error
```
file.v:2:7: error: invalid expression: unexpected `;` token
    1 | fn main() {
    2 |     a = i;
      |          ^
    3 | }

vfmt error while formatting file: file.v .
Encountered a total of: 1 errors.
```

**Comment by kahsa** [comment]
closed by mistake

**Comment by nedpals** [comment]
Closed as it is fixed in the latest version of vscode-vlang.
