### ISSUE TITLE
0.1.6 does not format

### ISSUE THREAD

**Issue by kahsa** [vlang/vscode-vlang#200]
vscode gives a message `There is no formatter for 'v' files installed.`

It's OK when both 0.1.3 and 0.1.6 are installed.

**Comment by danieldaeschle** [comment]
newest version of vls can handle it.

**Comment by JalonSolov** [comment]
Uninstall both 0.1.3 and 0.1.6, then install 0.1.7 from the marketplace.  It should auto-update from now on.

**Comment by lukeed** [comment]
I only have `0.1.7` installed (with vls) and there's VSCode doesn't recognize it as a formatter.
FWIW, there are only 3 extension settings now. I remember there being quite a bit more in the past.
