### ISSUE TITLE
.c.v: #include "" or #include <> makes following code not highlighted

### ISSUE THREAD

**Issue by IngwiePhoenix** [vlang/vscode-vlang#203]
Consider this:

```
#include "stdio.h"
fn C.puts(charptr) int
fn main() {
  C.puts("test")
}
```

Anything after that `#include` tag will not be highlighted correctly.

Version: 0.1.3
![image](https://user-images.githubusercontent.com/2893716/103746914-1fe21900-5002-11eb-9df6-88809514fb09.png)

**Comment by IngwiePhoenix** [comment]
What it shows:
![image](https://user-images.githubusercontent.com/2893716/103747033-4d2ec700-5002-11eb-8e36-7d344dbca655.png)

Removing the quotes:
![image](https://user-images.githubusercontent.com/2893716/103747061-5881f280-5002-11eb-8bd0-5f3d01563534.png)

**Comment by nedpals** [comment]
@IngwiePhoenix try the latest extension on the releases page since I think was fixed here: https://github.com/vlang/vscode-vlang/commit/d3404d4772ab744fe68361486c81fc6bb0058101

**Comment by ken0x0a** [comment]
I tried with `v0.1.7` and it works!
Thank you!

So, I think this issue can be closed.
