### ISSUE TITLE
Two versions on the extension marketplace.

### ISSUE THREAD

**Issue by ChildishGiant** [vlang/vscode-vlang#206]
![image](https://user-images.githubusercontent.com/13716824/104970803-96a8ea00-59e4-11eb-8600-946c9507c80c.png)

There's vlang-vscode.extension which is on version v0.1.3 and vlanguage.vscode-vlang which is on version v0.1.7, this being the one [vlang.io](https://vlang.io/) points to. Both of these point to this repo. Which is the de facto version and should the other be removed?

**Comment by JalonSolov** [comment]
The higher numbered one is the correct, latest version.  The older one was created by someone else, and we do not have the credentials to be able to remove it.
