### ISSUE TITLE
Published twice on marketplace?

### ISSUE THREAD

**Issue by mindplay-dk** [vlang/vscode-vlang#210]
How come the package is published twice on the VS Code marketplace?

Once under the name `vlang-vscode.extension` and again as `vlanguage.vscode-vlang`.

The second package has version `0.1.7`, the second has version `0.1.3` - but the one with the lower version number appears to have the latest features?

Pretty confusing and probably `vlanguage.vscode-vlang` should be removed?

![image](https://user-images.githubusercontent.com/103348/107222069-beec9d00-6a14-11eb-8c83-876bc38854ed.png)

**Comment by JalonSolov** [comment]
The `0.1.3` version was published by someone else, and we have not been able to contact him to get him to remove it.

The `0.1.7` version is the most recent version, with greatly updated features from the `0.1.3` version.

**Comment by nedpals** [comment]
We should add an information on the README about it

**Comment by medvednikov** [comment]
I've contacted Microsoft. They reply within 3 weeks, should get removed soon.

**Comment by muuvmuuv** [comment]
Better keep that open and pinned for others until it's taken down? Took me a while honestly finding out there are two ^^
