### ISSUE TITLE
Vweb snippets

### ISSUE THREAD

**Issue by Zerotask** [vlang/vscode-vlang#215]
I suggest adding snippets to provide an easy way of working with the web framework Vweb.

For the beginning, there could be snippets to create endpoints:

`vweb_get_products` could generate the following code:
```v
pub fn (mut app App) products() vweb.Result {
	// TODO
}
```

`vweb_post_products` could generate the following code:
```v
[post]
pub fn (mut app App) products() vweb.Result {
	// TODO
}
```

and to create the struct for the App:
`vweb_app` could generate the following code:
```v
struct App {
	vweb.Context
}
```

**Comment by medvednikov** [comment]
Sounds good.

**Comment by Zerotask** [comment]
Don't know if it's possible how I imagined that, but I made a PR which is more like you are used to in VSCode.
#216
