### ISSUE TITLE
The dot "." accessor operator has no grammar.

### ISSUE THREAD

**Issue by pouyakary** [vlang/vscode-vlang#246]
Hi. I'm the author of [Pro Colors](https://marketplace.visualstudio.com/items?itemName=karyfoundation.theme-karyfoundation-themes) and I'm trying to add support for V. So far it has been a challenge since the grammar does not specify the grammar for the identifiers and Pro Colors has to render all the identifiers blue. The trick so far was to render the `source.v` as blue and then color everything else so that the only thing that remains in the `source.v` be the identifiers. I have done this successfully but only got to problems (for now) with two grammar elements. One is the `.` that is used to access the methods of the classes:

<img width="679" alt="Screen Shot 1400-05-02 at 02 26 32" src="https://user-images.githubusercontent.com/2157285/126870241-e83111e0-fb46-4c10-925e-2a114e8ad800.png">

If this could be added to the grammar that could be awesome and I can have a full support for V in the Pro Colors :)

**Comment by pouyakary** [comment]
P.S. I'm willing to add it myself, I just didn't know where it is expected to be. If you give me a hint I'll add it myself.

**Comment by danieldaeschle** [comment]
I have no clue too. I will look into it next beginning of next month. I'm very new to text mate grammar.

If you PR it, please add tests as well.

**Comment by pouyakary** [comment]
Okay, if I did it before the month's ending I'll PR it, otherwise I tell you I couldn't
