### ISSUE TITLE
Does Vlang have a debugger for vcode?

### ISSUE THREAD

**Issue by TerryJoo** [vlang/vscode-vlang#358]
If you already have it, please recommend it.
If V don't have a debugger for vscode yet, I'm going to make it.

**Comment by nedpals** [comment]
@TerryJoo Hi! The debugger used for V are the same tools used for debugging C/C++. You can check them here: https://github.com/vlang/v/blob/master/doc/vscode.md#visual-debugging

**Comment by TerryJoo** [comment]
Thank you @nedpals !
