### ISSUE TITLE
It would be great if there was an auto-completion feature

### ISSUE THREAD

**Issue by tzSharing** [vlang/vscode-vlang#369]
hope that subsequent versions can add the auto-completion function

**Comment by JalonSolov** [comment]
That was added in #152

**Comment by tzSharing** [comment]
> That was added to vls in [vlang/vls#152](https://github.com/vlang/vls/pull/152)

Oh I get it. The v plugin must work with vls, and vls has implemented the auto-completion function. I didn't know vls before, I only installed the v plugin but did not open vls. However, I think the usage and setup documentation needs to be improved.
