### ISSUE TITLE
Support IntelliSense 

### ISSUE THREAD

**Issue by Nagkei10** [vlang/vscode-vlang#40]

**Comment by donnisnoni95** [comment]
@keito940 Soon... after https://github.com/nedpals/v-jsonrpc done

**Comment by JesterOrNot** [comment]
That would be amazing

**Comment by kokizzu** [comment]
this is for the autocomplete feature right?

**Comment by ChildishGiant** [comment]
Has anyone started work on this?

**Comment by unlimitedcoder2** [comment]
Any update on this?

**Comment by kahsa** [comment]
longing for it.....

**Comment by medvednikov** [comment]
This is being worked on.

**Comment by danieldaeschle** [comment]
This issue will be tracked here instead: https://github.com/vlang/vls/issues/4
