### ISSUE TITLE
No intellisense working at all

### ISSUE THREAD

**Issue by grab-a-byte** [vlang/vscode-vlang#512]
I have installed V on windows using the instructions from "Installing V from source" at https://github.com/vlang/v/blob/master/doc/docs.md#installing-v-from-source . 

I have installed the plugin in VSCode and create a new V project using the "v new" command and opened the folder in VSCode. 

Upon trying to use any intellisense (such as getting the type name of a sum type as shown here https://github.com/vlang/v/blob/master/doc/docs.md#sum-types) there is no intellisense at all. 

![image](https://user-images.githubusercontent.com/30392071/216666090-8e08978a-dbec-49b1-aed7-b616bd47b6dc.png)

Just a list of things already used or defined.

I have tried running VSCode as admin but insure what else to try. When trying to run the "Update VLS" command I am simply given a error which states 

``` 
Spawning v ls --json --update...
Error: spawn v ENOENT
````

Unsure if this is relevant and what I am missing for this to work. Any help would be much appreciated.

**Comment by parkeradam** [comment]
Any news or update on this?

**Comment by medvednikov** [comment]
vls is unstable unfortunately

intellij v is much better, but we'll make vls just as stable

will take a couple of months though

**Comment by xjzh123** [comment]
*Not formally
Vuck, it veels like that VSCode is discriminated against by the community.

**Comment by alfu32** [comment]
Same under Ubuntu 22. Simply doesn’t work anymore.

How can I help ? ( I’ve got 0 exp with vscode extensions )
Where do I need to start in your code ?

**Comment by MARCROCK22** [comment]
any updates on this? i'm trying to learn vlang but the lack of intellisense and telling me a syntax error/type error before running the code is... annoying
