### ISSUE TITLE
WIN10  module in .vmodule not found 

### ISSUE THREAD

**Issue by osascruz** [vlang/vscode-vlang#536]
PROBLEMS  says  "Module  xxx.yyy not found"        ( xxxx.yyyy is format reference to github)
 module is installed  %USERPROFILE%/.vmodule/xxxx/yyyy 
 
How to add a  PATH to  vscode-vlang ?  how to fix this  ? 

thank you very much !

**Comment by ttytm** [comment]
There is a new extension with extended features that is recommended for V development in VS Code, it is called v-analyzer.

This is the repo: https://github.com/v-analyzer/v-analyzer
You can also find it via the marketplace (when searching the extensions): https://marketplace.visualstudio.com/items?itemName=VOSCA.vscode-v-analyzer

**Comment by osascruz** [comment]
thank you very much !!!
